### ISSUE TITLE
Inference cost

### ISSUE THREAD

**Issue by tengyu-liu** [OpenGVLab/unmasked_teacher#11]
Great work! The performance on public sources is very impressive. Congratulations!

The paper did not mention the cost of inference. How many A100s do you need for inference?

**Comment by Andy1621** [comment]
It only requires one A100 for inference since the large model is only ViT-large.
For retrieval, if you dataset is too large, maybe you need more GPUs to have a quick inference.

**Comment by tengyu-liu** [comment]
Thank you very much. I'm closing this issue.
