### ISSUE TITLE
video-text retrieval MSVD数据集划分

### ISSUE THREAD

**Issue by SuperHalo** [OpenGVLab/unmasked_teacher#12]
您好！我想用您的代码复现一下MSVD数据集的结果，下图是用l16_25m微调后的模型测试的结果。与论文结果不一致，应该是数据划分不一样导致的。MSVD数据集的文本标注原本是一对多，但是根据论文Table28对MSVD数据集的描述，对于每个视频，您只从对应的文本标注取了一个文本吗？能否提供您的标注json文件？谢谢！
![image](https://github.com/OpenGVLab/unmasked_teacher/assets/55133120/36453e14-2a7f-495e-92a2-a84d1ce9dd8c)

**Comment by Andy1621** [comment]
您好，见下载链接https://drive.google.com/drive/folders/1eY1WYFLrWzY3RJRk35LOlouiVOT0QYyL?usp=drive_link

**Comment by SuperHalo** [comment]
谢谢您的及时回复与分享！使用您的数据标注文件的测试结果仍与论文中的不同。能否麻烦您帮我看看是否有参数设置与您论文结果对应的设置不一样。我使用的模型是ret_msvd_l16_25m.pth。非常感谢！！
[msvd_l16.md](https://github.com/OpenGVLab/unmasked_teacher/files/12657154/msvd_l16.md)

**Comment by Andy1621** [comment]
能否提供完整的训练/测试log呢？

**Comment by SuperHalo** [comment]
这是测试的log，您看看，谢谢
[msvd_l16.log](https://github.com/OpenGVLab/unmasked_teacher/files/12659816/msvd_l16.log)

**Comment by Andy1621** [comment]
可以查看[google drive](https://drive.google.com/drive/folders/1lf48xTGC5mhapnnS_39mDy65m3zq1zXF?usp=sharing)，我上传了之前实验训练和测试的log，您可以对照着看看有无问题，最近比较忙，实在难以帮忙debug

**Comment by SuperHalo** [comment]
谢谢，是我这边的参数设置跟您不一样，已经复现出论文的结果了

**Comment by Andy1621** [comment]
我抽空查了下bug，可以看看这个[warning](https://github.com/OpenGVLab/unmasked_teacher/blob/8e06491336f8b1692b4ffafd99d23d0fadf362d3/multi_modality/dataset/caption_dataset.py#L110-L122)

**Comment by SuperHalo** [comment]
非常感谢！请问能再给一下video-text retrieval任务其他数据集的标注文件吗？包括DiDeMo，ActivityNet，LSMDC

**Comment by Andy1621** [comment]
可以从VINDLU共享的文件中转换https://drive.google.com/drive/folders/12cr94wT8j7pR09AR2nmQg6o26Y1arI50

**Comment by Andy1621** [comment]
测试结果已经更新
