### ISSUE TITLE
请教一下指标复现上出现的一些问题

### ISSUE THREAD

**Issue by Noobb123** [OpenGVLab/unmasked_teacher#13]
你好！最近学习了老哥的UMT，感觉算法性能很强大，想实操一下代码，但是使用stage-2模型（l16_25m.pth）在didemo和msvd上没有跑出论文中的指标。
目前最大的gap是我使用了单卡单机做的实验，其它的基本没有修改，想向老哥请教一下，我哪里操作有问题，感谢！

![msvd](https://github.com/OpenGVLab/unmasked_teacher/assets/109051102/58d0e558-11ef-43aa-b972-a37525291d39)
[train.log](https://github.com/OpenGVLab/unmasked_teacher/files/12659525/train.log)
[config.json.txt](https://github.com/OpenGVLab/unmasked_teacher/files/12659604/config.json.txt)
（附上配置文件和评测log）

**Comment by Andy1621** [comment]
可以查看[google drive](https://drive.google.com/drive/folders/1lf48xTGC5mhapnnS_39mDy65m3zq1zXF?usp=sharing)，我上传了之前实验训练和测试的log，您可以对照着看看有无问题，最近比较忙，实在难以帮忙debug

**Comment by Noobb123** [comment]
> 可以查看[google drive](https://drive.google.com/drive/folders/1lf48xTGC5mhapnnS_39mDy65m3zq1zXF?usp=sharing)，我上传了之前实验训练和测试的log，您可以对照着看看有无问题，最近比较忙，实在难以帮忙debug

好的，我再学习一下，感谢！

**Comment by Andy1621** [comment]
我抽空查了下bug，可以看看这个[warning](https://github.com/OpenGVLab/unmasked_teacher/blob/8e06491336f8b1692b4ffafd99d23d0fadf362d3/multi_modality/dataset/caption_dataset.py#L110-L122)，后面会更新下结果

**Comment by Noobb123** [comment]
> 我抽空查了下bug，可以看看这个[warning](https://github.com/OpenGVLab/unmasked_teacher/blob/8e06491336f8b1692b4ffafd99d23d0fadf362d3/multi_modality/dataset/caption_dataset.py#L110-L122)，后面会更新下结果

感谢老哥帮忙debug哈！
代码上没啥问题，很完整和流畅。我这边尝试启动了一下标记符trimmed30和is_paragraph_retrieval，评测结果基本上和论文指标相似了。很棒的工作，还在持续学习

**Comment by Andy1621** [comment]
加油
