### ISSUE TITLE
Problem with downloading  Video Question Answering ActivityNet-QA ckpt 

### ISSUE THREAD

**Issue by nonomanlurker** [OpenGVLab/unmasked_teacher#15]
![Screenshot 2023-09-28 150236](https://github.com/OpenGVLab/unmasked_teacher/assets/132457242/6577695e-89b3-499a-af1f-ca1588889b74)
![image](https://github.com/OpenGVLab/unmasked_teacher/assets/132457242/35da6d60-ea21-4d1d-9c0b-6aa35d55c4c5)

Hello, thank you for your great work. I encountered two errors when downloading the multimodality VQA ActivityNet-QA checkpoint. How could I fix it?

**Comment by Andy1621** [comment]
I have updated the link~
