### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by JackSparrow3** [OpenGVLab/unmasked_teacher#19]
很棒的工作！感谢分享。我在跑单卡训练msrvtt demo时候，GPU显存随着每次迭代都在涨，然后马上爆显存，不知道作者有没有遇到过？

**Comment by Andy1621** [comment]
没有遇到过呢

**Comment by JackSparrow3** [comment]
> 没有遇到过呢
貌似是我的版本问题，在训练的时候关闭了checkpoint这个就解决了。
