### ISSUE TITLE
Include code

### ISSUE THREAD

**Issue by nathankaha** [OpenGVLab/unmasked_teacher#2]
Hi i'm working on a project and I'd like to use your model for it, so I'd like to know when do you estimate that the code and the pretrained checkpoints will be released?
Thanks for your incredible work it looks great hopefully I'll be able to try it soon.

**Comment by Andy1621** [comment]
Thanks for your question! The code and model will be released in June-July.

**Comment by Andy1621** [comment]
@nathankaha All the code and models are released. Have a try and don't hesitate to open an issue if you meet any problem.
