### ISSUE TITLE
An example showing how to do fine running

### ISSUE THREAD

**Issue by mustafahalimeh** [OpenGVLab/unmasked_teacher#20]
Thanks for your work.
I tried to get one model from the Model Zoo, but when I tried to load it using PyTorch it returns OrderedDict object.
model = torch.load('l16_ptk710_ftk710_f8_res224.pth')
Would you please give a use-case example how to load the saved check point into a model and then fine tune it.

**Comment by Andy1621** [comment]
Please refer to the [`finetuning`](https://github.com/OpenGVLab/unmasked_teacher/tree/main/single_modality#finetuning).

**Comment by MH-Python** [comment]
Is there a cutom pre-processing funtion when preparing the downstream task data for the fine-tuning?
Or it is enough to do:

```
_frames, _audio, _info = torchvision.io.read_video(video_path, pts_unit='sec', output_format='THWC')
_frames = _frames.float() / 255
_clips = _clips.permute(0, 4, 1, 2, 3).contiguous()
_clips = F.interpolate(_clips, size=(16, 224, 224), mode="trilinear")
_clips = _clips - torch.tensor([0.485, 0.456, 0.406]).view(1, -1, 1, 1, 1)
_clips = _clips / torch.tensor([0.229, 0.224, 0.225]).view(1, -1, 1, 1, 1)
```
