### ISSUE TITLE
Some json files are missing

### ISSUE THREAD

**Issue by cmh1027** [OpenGVLab/unmasked_teacher#22]
Hello, I'm looking for QA msvd json file. I found retrieval msvd json file in [here](https://github.com/OpenGVLab/unmasked_teacher/issues/12), but where is the one for QA?

**Comment by Andy1621** [comment]
Check it [here](https://drive.google.com/drive/folders/1eY1WYFLrWzY3RJRk35LOlouiVOT0QYyL?usp=sharing)

**Comment by cmh1027** [comment]
@Andy1621 Thanks. Could you also provide me with json files of lsmdc dataset?

**Comment by cmh1027** [comment]
@Andy1621 Thanks for fast reply! I have one more question
![image](https://github.com/OpenGVLab/unmasked_teacher/assets/22341329/ffb48016-a161-4d9d-8133-1d39cf5c9cb1)
This is a zero-shot retrieval result on MSVD dataset using l16_25m.pth. Could you guess why img_r1 is so low compared to the table in the repo?

**Comment by Andy1621** [comment]
The results are correct! I have updated the results in [MODEL_ZOO](https://github.com/OpenGVLab/unmasked_teacher/blob/main/multi_modality/MODEL_ZOO.md) a few days ago. The results are lower because I have fixed the bug, where I used `is_paragraph_retrieval=True`.

**Comment by cmh1027** [comment]
![image](https://github.com/OpenGVLab/unmasked_teacher/assets/22341329/d244a3aa-e920-42a2-ab80-96b92c49b275)

@Andy1621 Did you also update the table of fine-tuning retrieval on msvd? This is a result of fine-tuning retrieval using b16_25m.pth and it looks like much lower than the one in the table.

**Comment by Andy1621** [comment]
Have you used the new script? Please check the [log](https://drive.google.com/file/d/1LbJ93wryplwSBjSA51ODNcH4y8FY4bR4/view?usp=sharing).

**Comment by cmh1027** [comment]
The checkpoint I have to use should be downloaded from this [url](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/umt/multi_modality/ret_msvd_b16_25m.pth) right?

**Comment by Andy1621** [comment]
No, you should download the pretrained model, which you use for zero-shot testing.

**Comment by cmh1027** [comment]
![image](https://github.com/OpenGVLab/unmasked_teacher/assets/22341329/c73e3be5-35ac-4d6e-ad55-73c8a5f33431)
I want to reproduce the result of this table, but isn't this table referring to the results of fine-tuned model, not zero-shot?

**Comment by Andy1621** [comment]
Please check the caption for each table in detail.
