### ISSUE TITLE
Question about test video number of didemo retrieval

### ISSUE THREAD

**Issue by allonsy07** [OpenGVLab/unmasked_teacher#23]
Thanks for great research.

In your paper, I found the number of test video is 1,036,
but in json file from [Googe drive](https://drive.google.com/drive/folders/12bC7WotvwyTG4pVvYeU4iZzmBLP1-6d9) has 1,003 test videos, and I reproduced different scores with in paper.

Is there something that I missed?

**Comment by Andy1621** [comment]
Check my file [here](https://drive.google.com/drive/folders/1hWtLHbVf5CecEAYiz8of9qrArZKZjfxQ?usp=sharing).

**Comment by allonsy07** [comment]
Thank you for getting back to me.

Why is there a difference between your file and [VINDLU](https://drive.google.com/drive/folders/12bC7WotvwyTG4pVvYeU4iZzmBLP1-6d9) you liked in READMD?

**Comment by Andy1621** [comment]
I'm not sure. The files I used were transformed from our previous retrieval metafiles.
