### ISSUE TITLE
Wrong Checkpoint in Model Zoo (Multimodal)

### ISSUE THREAD

**Issue by HyeongminLEE** [OpenGVLab/unmasked_teacher#26]
Hi, I'm trying to download and analyze the checkpoints you opened.
During analyzing, I found that a wrong ckpt has been uploaded.

In the b16_25m.pth in `https://github.com/OpenGVLab/unmasked_teacher/blob/main/multi_modality/MODEL_ZOO.md`,
There's no keys `vision_proj`, `text_proj`, `itm_head`, `clip_teacher` and it includes `text_decoder` which other checkpoints do not include.
Is it intended?
Or not, it would be helpful for improving this repo to re-uploading the ckpt.

Thanks!

**Comment by Andy1621** [comment]
Have you downloaded the correct models? It seemed normal when I checked.
<img width="326" alt="image" src="https://github.com/OpenGVLab/unmasked_teacher/assets/24236723/cf36df09-6980-4a67-bd6d-7273bce32b09">

**Comment by HyeongminLEE** [comment]
Following the link on the table shared at `OpenGVLab/unmasked_teacher/blob/main/multi_modality/MODEL_ZOO.md`, I downloaded the b16_25m and b16_17m models by following command.

`wget https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/umt/multi_modality/b16_25m.pth`
`wget https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/umt/multi_modality/b16_17m.pth`

Then I checked the keys of the two checkpoints.
Then I got following result

![image](https://github.com/OpenGVLab/unmasked_teacher/assets/25631557/c11e49fe-2155-4c4d-9102-0ee8e78ee743)

**Comment by Andy1621** [comment]
Thanks for your responses! We have updated the checkpoints. The previous checkpoints were overwritten by mistake.

**Comment by HyeongminLEE** [comment]
Thanks! It works now.
