### ISSUE TITLE
conda env conflict

### ISSUE THREAD

**Issue by pengzhansun** [OpenGVLab/unmasked_teacher#29]
Thanks for make this amazing work publicly available. I encounter some dependency conflict problems when trying to build the conda environment.

> Collecting package metadata (repodata.json): ...working... done
> Solving environment: ...working... 
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed
> Solving environment: ...working... 
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed

Any idea to handle this?

**Comment by Andy1621** [comment]
Sorry, I have not met your problem. And I'm not sure whether it's because of the wrong version of CUDA.

**Comment by lizenan** [comment]
> Sorry, I have not met your problem. And I'm not sure whether it's because of the wrong version of CUDA.

could you provide your version specs please?

**Comment by Andy1621** [comment]
I use cuda11.7~

**Comment by kaizhuanren** [comment]
My nvcc -V is also 11.7,but I met the similar questions,since you have already change the issue into closed,how did you solve it

> 感谢您公开发布这项出色的工作。我在尝试构建 conda 环境时遇到了一些依赖冲突问题。
> 
> > 收集包元数据 (repodata.json)：...工作...完成
> > 解决环境：...工作...
> > 发现冲突！正在寻找不兼容的包。
> > 这可能需要几分钟。按 CTRL-C 中止。
> > 失败
> > 解决环境：...工作...
> > 发现冲突！正在寻找不兼容的包。
> > 这可能需要几分钟。按 CTRL-C 中止。
> > 失败
> 
> 有什么想法可以解决这个问题吗？

**Comment by kaizhuanren** [comment]
> > Sorry, I have not met your problem. And I'm not sure whether it's because of the wrong version of CUDA.
> 
> could you provide your version specs please?

My nvcc -V is also 11.7,but I met the similar questions,,have you solved it
