### ISSUE TITLE
CLIP as teacher

### ISSUE THREAD

**Issue by farewellthree** [OpenGVLab/unmasked_teacher#3]
Hi, congratulation on the great results!
I'm curious about the results of vanilla CLIP being a teacher, is there any ablation on this? Besides, it seems that CLIP-ViP does not have an L/14 version.
Thanks.

**Comment by Andy1621** [comment]
Sorry for the late response. 

I don't get the meaning of your problem with the `vanilla CLIP`. In our experiments, we indeed adopt the vanilla CLIP-B/16 for UMT-B/16 and CLIP-L/14 for UMT-L/14.
