### ISSUE TITLE
single_modality pip install raise AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.

### ISSUE THREAD

**Issue by vba34520** [OpenGVLab/unmasked_teacher#32]
```shell
cd single_modality

pip install -r requirements.txt
```

It raised `AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.`

**Comment by Andy1621** [comment]
Thanks for your question. You can change the order in `requirements.txt` and install `torch` firstly.

**Comment by vba34520** [comment]
Thank you for your job!

I find a solution like this:

```shell
pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113
```

references [Previous PyTorch Versions](https://pytorch.org/get-started/previous-versions/#v1121)
