### ISSUE TITLE
Missing files for SSv2

### ISSUE THREAD

**Issue by ninatu** [OpenGVLab/unmasked_teacher#37]
Hi! It seems like train.csv, test.csv, val.csv files for SSv2 are missing in shared Google Drive (actually entire ssv2 folder is missing). Could you kindly add them?

**Comment by Andy1621** [comment]
Hi! For ssv2, we simply change the `txt` files into csv~

**Comment by Andy1621** [comment]
Hi! I also upload the files in [Google Drive](https://drive.google.com/drive/folders/1C1wCGTBIsD-5sKafaaLikgusOH37FDIY?usp=sharing). Please check.
