### ISSUE TITLE
config_dp01lr2w1e12_trimmed30.py

### ISSUE THREAD

**Issue by tqosu** [OpenGVLab/unmasked_teacher#40]
Dear authors,

Where can I find config_dp01lr2w1e12_trimmed30.py in multi_modality/exp/finetuning/ret_didemo/b16_25m.sh?

**Comment by Andy1621** [comment]
Hi! It is `multi_modality/exp/finetuning/ret_didemo/b16_25m.py`, and I forget to change the file name.

**Comment by tqosu** [comment]
Thanks.
